using System.Collections.Immutable;

namespace SourceExpander.Generate.Config;

public class EmbeddingSourceClassNameTest : EmbedderGeneratorTestBase
{
    [Test]
    public async Task EmbeddingSourceClassNone(CancellationToken cancellationToken)
    {
        const string embeddedSourceCode = """[{"CodeBody":"class Program{static void Main(){Debug.Assert(true);Console.WriteLine(1);}}","Dependencies":[],"FileName":"TestProject>Program.cs","TypeNames":["Program"],"Usings":["using System;","using System.Diagnostics;"]}]""";
        await embeddedSourceCode.Should().BeEquivalentToJsonSources([
             new SourceFileInfo
             (
                 "TestProject>Program.cs",
                 ["Program"],
                 ImmutableArray.Create("using System;", "using System.Diagnostics;"),
                 ImmutableArray<string>.Empty,
                 """class Program{static void Main(){Debug.Assert(true);Console.WriteLine(1);}}"""
             )
        ]);

        var test = new Test(new()
        {
            EmbeddedSourceCode = embeddedSourceCode,
        })
        {
            TestState =
            {
                AdditionalFiles =
                {
                    (
                    "/foo/bar/SourceExpander.Embedder.Config.json",
                    """
                    {
                        "$schema": "https://raw.githubusercontent.com/kzrnm/SourceExpander/master/schema/embedder.schema.json",
                        "embedding-type": "Raw",
                        "embedding-source-class-name": null,
                        "minify-level": "full"
                    }
                    """),
                    ("/foo/bar/SourceExpander.Notmatch.json", "notmatch"),
                },
                Sources = {
                    (
                        "/home/source/Program.cs",
                        """
                        using System;
                        using System.Diagnostics;

                        class Program
                        {
                            static void Main()
                            {
                                Debug.Assert(true);
                                Console.WriteLine(1);
                            }
                        }
                        """
                    ),
                },
            }
        };
        await test.RunAsync(cancellationToken);
    }

    [Test]
    public async Task EmbeddingSourceClass(CancellationToken cancellationToken)
    {
        const string embeddedSourceCode = """[{"CodeBody":"class Program{static void Main(){Debug.Assert(true);Console.WriteLine(1);}}","Dependencies":[],"FileName":"TestProject>Program.cs","TypeNames":["Program"],"Usings":["using System;","using System.Diagnostics;"]}]""";
        await embeddedSourceCode.Should().BeEquivalentToJsonSources([
             new SourceFileInfo
             (
                 "TestProject>Program.cs",
                 ["Program"],
                 ImmutableArray.Create("using System;", "using System.Diagnostics;"),
                 ImmutableArray<string>.Empty,
                 """class Program{static void Main(){Debug.Assert(true);Console.WriteLine(1);}}"""
             )
        ]);

        var test = new Test(new()
        {
            EmbeddedSourceCode = embeddedSourceCode,
        })
        {
            TestState =
            {
                AdditionalFiles =
                {
                    (
                    "/foo/bar/SourceExpander.Embedder.Config.json", """
                    {
                        "$schema": "https://raw.githubusercontent.com/kzrnm/SourceExpander/master/schema/embedder.schema.json",
                        "embedding-type": "Raw",
                        "embedding-source-class-name": "Container",
                        "minify-level": "full"
                    }
                    """),
                    ("/foo/bar/SourceExpander.Notmatch.json", "notmatch"),
                },
                Sources = {
                    (
                        "/home/source/Program.cs",
                        """
                        using System;
                        using System.Diagnostics;

                        class Program
                        {
                            static void Main()
                            {
                                Debug.Assert(true);
                                Console.WriteLine(1);
                            }
                        }
                        """
                    ),
                },
                GeneratedSources =
                {
                    (typeof(EmbedderGenerator), "EmbeddingSourceClass.cs",
                    EnvironmentUtil.JoinByStringBuilder(
                        "// <auto-generated/>",
                        "#pragma warning disable",
                        "namespace SourceExpander.Embedded{",
                        "using System;",
                        "using System.Collections.Generic;",
                        "public class Container{",
                        "public class SourceFileInfo{",
                        "  public string FileName{get;set;}",
                        "  public string[] TypeNames{get;set;}",
                        "  public string[] Usings{get;set;}",
                        "  public string[] Dependencies{get;set;}",
                        "  public string CodeBody{get;set;}",
                        "}",
                        "  public static readonly IReadOnlyList<SourceFileInfo> Files = new SourceFileInfo[]{",
                        "    new SourceFileInfo{",
                        "      FileName = \"TestProject>Program.cs\",",
                        "      CodeBody = \"class Program{static void Main(){Debug.Assert(true);Console.WriteLine(1);}}\",",
                        "      TypeNames = new string[]{",
                        "        \"Program\",",
                        "      },",
                        "      Usings = new string[]{",
                        "        \"using System;\",",
                        "        \"using System.Diagnostics;\",",
                        "      },",
                        "      Dependencies = new string[]{",
                        "      },",
                        "    },",
                        "  };",
                        "}",
                        "}")
                    ),
                }
            }
        };
        await test.RunAsync(cancellationToken);
    }
}
