namespace SourceExpander.Generate.Config;

public class VersionOnlyTest : EmbedderGeneratorTestBase
{
    [Test]
    public async Task VersionOnlyProperty(CancellationToken cancellationToken)
    {
        var test = new Test
        {
            AnalyzerConfigOptions =
            {
                { "build_property.SourceExpander_Embedder_VersionOnly", "true" },
            },
            TestState =
            {
                Sources = {
                    (
                        "/home/source/Program.cs",
                        """
using System;
using System.Diagnostics;

[DebuggerDisplay("Name")]
class Program
{
    static void Main()
    {
        Console.WriteLine(1);
    }

    [System.Diagnostics.Conditional("TEST")]
    static void T() => Console.WriteLine(2);
}
"""
                    ),
                },
                GeneratedSources =
                {
                    (typeof(EmbedderGenerator), "EmbeddedSourceCode.Metadata.cs",
                    $$"""
                    // <auto-generated/>
                    #pragma warning disable
                    [assembly: global::System.Reflection.AssemblyMetadataAttribute("SourceExpander.EmbedderVersion","{{EmbedderVersion}}")]
                    """
                    )
                }
            }
        };
        await test.RunAsync(cancellationToken);
    }
}
