//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceExpander.Diagnostics {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DiagnosticsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiagnosticsResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SourceExpander.Diagnostics.DiagnosticsResources", typeof(DiagnosticsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Unknown error: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMBED0001_Body {
            get {
                return ResourceManager.GetString("EMBED0001_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMBED0001_Title {
            get {
                return ResourceManager.GetString("EMBED0001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Embeder version({0}) is older than embedder of {1}({2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMBED0002_Body {
            get {
                return ResourceManager.GetString("EMBED0002_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Embeder version is older に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMBED0002_Title {
            get {
                return ResourceManager.GetString("EMBED0002_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error config file: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMBED0003_Body {
            get {
                return ResourceManager.GetString("EMBED0003_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error config file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMBED0003_Title {
            get {
                return ResourceManager.GetString("EMBED0003_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error embedded source: File: {0}, Message: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMBED0004_Body {
            get {
                return ResourceManager.GetString("EMBED0004_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error embedded source に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMBED0004_Title {
            get {
                return ResourceManager.GetString("EMBED0004_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Different syntax: near {0}. This is Embedder error, please report this to GitHub repository. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMBED0005_Body {
            get {
                return ResourceManager.GetString("EMBED0005_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Different syntax に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMBED0005_Title {
            get {
                return ResourceManager.GetString("EMBED0005_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Another assembly has invalid embedded data: {0}, Key: {1}, Message: {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMBED0006_Body {
            get {
                return ResourceManager.GetString("EMBED0006_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Another assembly has invalid embedded data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMBED0006_Title {
            get {
                return ResourceManager.GetString("EMBED0006_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nullable option is unsupported に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMBED0007_Title {
            get {
                return ResourceManager.GetString("EMBED0007_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nullable directive is unsupported に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMBED0008_Title {
            get {
                return ResourceManager.GetString("EMBED0008_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avoid using static directive because there is a risk of name collision に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMBED0009_Body {
            get {
                return ResourceManager.GetString("EMBED0009_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avoid using static directive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMBED0009_Title {
            get {
                return ResourceManager.GetString("EMBED0009_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avoid using alias directive because there is a risk of name collision に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMBED0010_Body {
            get {
                return ResourceManager.GetString("EMBED0010_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avoid using alias directive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMBED0010_Title {
            get {
                return ResourceManager.GetString("EMBED0010_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}: Obsolete embedder config property. {1} is obsolete. Use {2}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMBED0011_Body {
            get {
                return ResourceManager.GetString("EMBED0011_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Obsolete embedder config property に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMBED0011_Title {
            get {
                return ResourceManager.GetString("EMBED0011_Title", resourceCulture);
            }
        }
    }
}
