using System.Threading.Tasks;
using Microsoft.CodeAnalysis.Testing;

namespace SourceExpander.Generate
{
    public class CompilationErrorTest : EmbedderGeneratorTestBase
    {
        [Fact]
        public async Task Generate()
        {
            var test = new Test
            {
                TestState =
                {
                    AdditionalFiles =
                    {
                        enableMinifyJson,
                    },
                    Sources = {
                        (
                            "home/test/Program.cs",
                            """
class Program
{
    public static int Method() => 1 + 2 ** 3;
}
"""
                        ),
                    },
                    GeneratedSources =
                    {
                        (typeof(EmbedderGenerator),
                            "EmbeddedSourceCode.Metadata.cs",
                            $$"""
// <auto-generated/>
#pragma warning disable
[assembly: global::System.Reflection.AssemblyMetadataAttribute("SourceExpander.EmbedderVersion","{{EmbedderVersion}}")]
[assembly: global::System.Reflection.AssemblyMetadataAttribute("SourceExpander.EmbeddedLanguageVersion","{{EmbeddedLanguageVersion}}")]
[assembly: global::System.Reflection.AssemblyMetadataAttribute("SourceExpander.EmbeddedNamespaces","")]
[assembly: global::System.Reflection.AssemblyMetadataAttribute("SourceExpander.EmbeddedSourceCode","[{\"CodeBody\":\"class Program{public static int Method()=>1+2* *3;}\",\"Dependencies\":[],\"FileName\":\"TestProject>Program.cs\",\"TypeNames\":[\"Program\"],\"Usings\":[]}]")]

"""
                        ),
                    },
                    ExpectedDiagnostics =
                    {
                        DiagnosticResult.CompilerWarning("EMBED0004"),
                        DiagnosticResult.CompilerError("CS0193").WithSpan("home/test/Program.cs", 3, 42, 3, 45),
                    },
                }
            };
            await test.RunAsync(TestContext.Current.CancellationToken);
        }
    }
}
