using System.Collections.Immutable;

namespace SourceExpander.Generate;

public class DefaultTest : EmbedderGeneratorTestBase
{
    [Test]
    public async Task MinifyRaw(CancellationToken cancellationToken)
    {
        var embeddedNamespaces = ImmutableArray<string>.Empty;
        const string embeddedSourceCode = """[{"CodeBody":"class Program{static void Main()=>Console.WriteLine(0);}","Dependencies":[],"FileName":"TestProject>Program.cs","TypeNames":["Program"],"Usings":["using System;"]}]""";
        await embeddedSourceCode.Should().BeEquivalentToJsonSources([
             new SourceFileInfo
             (
                 "TestProject>Program.cs",
                 ["Program"],
                 ImmutableArray.Create("using System;"),
                 ImmutableArray<string>.Empty,
                 """class Program{static void Main()=>Console.WriteLine(0);}"""
             ),
        ]);

        var test = new Test
        {
            TestState =
            {
                AdditionalFiles = { enableMinifyJson },
                Sources = {
                    (
                        "/home/source/Program.cs",
                        """
                        using System;
                        class Program
                        {
                            static void Main() => Console.WriteLine(0);
                        }
                        """
                    ),
                },
                GeneratedSources =
                {
                    (typeof(EmbedderGenerator), "EmbeddedSourceCode.Metadata.cs",$"""
                    // <auto-generated/>
                    #pragma warning disable
                    [assembly: global::System.Reflection.AssemblyMetadataAttribute("SourceExpander.EmbedderVersion","{EmbedderVersion}")]
                    [assembly: global::System.Reflection.AssemblyMetadataAttribute("SourceExpander.EmbeddedLanguageVersion","{EmbeddedLanguageVersion}")]
                    [assembly: global::System.Reflection.AssemblyMetadataAttribute("SourceExpander.EmbeddedNamespaces","{string.Join(",", embeddedNamespaces)}")]
                    [assembly: global::System.Reflection.AssemblyMetadataAttribute("SourceExpander.EmbeddedSourceCode",{embeddedSourceCode.ToLiteral()})]
                    
                    """
                    ),
                }
            }
        };
        await test.RunAsync(cancellationToken);
    }

    [Test]
    public async Task Generate(CancellationToken cancellationToken)
    {
        var embeddedNamespaces = ImmutableArray<string>.Empty;
        string embeddedSourceCode = SourceFileInfoUtil.ToGZipBase32768("[{\"CodeBody\":\"class Program { static void Main() => Console.WriteLine(0); }\",\"Dependencies\":[],\"FileName\":\"TestProject>Program.cs\",\"TypeNames\":[\"Program\"],\"Usings\":[\"using System;\"]}]");
        await SourceFileInfoUtil.FromGZipBase32768(embeddedSourceCode).Should().BeEquivalentToJsonSources([
             new SourceFileInfo
             (
                 "TestProject>Program.cs",
                 ["Program"],
                 ImmutableArray.Create("using System;"),
                 ImmutableArray<string>.Empty,
                 """class Program { static void Main() => Console.WriteLine(0); }"""
             ),
        ]);

        var test = new Test
        {
            TestState =
            {
                AdditionalFiles = { },
                Sources = {
                    (
                        "/home/source/Program.cs",
                        """
                        using System;
                        class Program
                        {
                            static void Main() => Console.WriteLine(0);
                        }

                        """
                    ),
                },
                GeneratedSources =
                {
                    (typeof(EmbedderGenerator), "EmbeddedSourceCode.Metadata.cs",
                    $"""
                    // <auto-generated/>
                    #pragma warning disable
                    [assembly: global::System.Reflection.AssemblyMetadataAttribute("SourceExpander.EmbedderVersion","{EmbedderVersion}")]
                    [assembly: global::System.Reflection.AssemblyMetadataAttribute("SourceExpander.EmbeddedLanguageVersion","{EmbeddedLanguageVersion}")]
                    [assembly: global::System.Reflection.AssemblyMetadataAttribute("SourceExpander.EmbeddedNamespaces","{string.Join(",", embeddedNamespaces)}")]
                    [assembly: global::System.Reflection.AssemblyMetadataAttribute("SourceExpander.EmbeddedSourceCode.GZipBase32768",{embeddedSourceCode.ToLiteral()})]
                    
                    """
                    ),
                }
            }
        };
        await test.RunAsync(cancellationToken);
    }
}
