using System.Collections.Immutable;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace SourceExpander.Generate
{
    public class PreProcessTest : EmbedderGeneratorTestBase
    {
        [Test]
        public async Task Generate()
        {
            var embeddedNamespaces = ImmutableArray<string>.Empty;
            var embeddedFiles = ImmutableArray.Create(
                 new SourceFileInfo
                 (
                     "TestProject>Program.cs",
                     ["Program"],
                     ImmutableArray.Create("using System;"),
                     ImmutableArray<string>.Empty,
                     "class Program{int[]v=new int[]{2,4,6,};static void Main()=>Console.WriteLine(1);}"
                 ));
            const string embeddedSourceCode = "[{\"CodeBody\":\"class Program{int[]v=new int[]{2,4,6,};static void Main()=>Console.WriteLine(1);}\",\"Dependencies\":[],\"FileName\":\"TestProject>Program.cs\",\"TypeNames\":[\"Program\"],\"Usings\":[\"using System;\"]}]";

            var test = new Test
            {
                ParseOptions = new CSharpParseOptions(
                    EmbeddedLanguageVersionEnum,


                    kind: SourceCodeKind.Regular,
                    documentationMode: DocumentationMode.Parse,
                    preprocessorSymbols: new[] { "Trace", "TEST" }),
                TestState =
                {
                    AdditionalFiles =
                    {
                        enableMinifyJson,
                    },
                    Sources = {
                        (
                            "/home/source/Program.cs",
// lang=C#
"""
using System;
class Program
{
    int[] v = new int[]
    {
#if SOURCE_EMBEDDINGA
    1,
#elif SOURCE_EMBEDDING
    2,
#else
    0,
#endif
#if !SOURCE_EMBEDDING
    3,
#else
    4,
#endif
#if SOURCE_EMBEDDING && NOT_DEFINED
    5,
#endif
#if NOT_DEFINED || SOURCE_EMBEDDING
    6,
#endif
    };
    static void Main() =>
#if TRACE
    Console.WriteLine(0);
#else
    Console.WriteLine(
#if TEST
1
#else
2
#endif
);
#endif
}
"""
                        ),
                    },
                    GeneratedSources =
                    {
                        (typeof(EmbedderGenerator), "EmbeddedSourceCode.Metadata.cs",$"""
                        // <auto-generated/>
                        #pragma warning disable
                        [assembly: global::System.Reflection.AssemblyMetadataAttribute("SourceExpander.EmbedderVersion","{EmbedderVersion}")]
                        [assembly: global::System.Reflection.AssemblyMetadataAttribute("SourceExpander.EmbeddedLanguageVersion","{EmbeddedLanguageVersion}")]
                        [assembly: global::System.Reflection.AssemblyMetadataAttribute("SourceExpander.EmbeddedNamespaces","{string.Join(",", embeddedNamespaces)}")]
                        [assembly: global::System.Reflection.AssemblyMetadataAttribute("SourceExpander.EmbeddedSourceCode",{embeddedSourceCode.ToLiteral()})]
                        
                        """
                        ),
                    }
                }
            };
            await test.RunAsync(TestContext.Current!.Execution.CancellationToken);
            Newtonsoft.Json.JsonConvert.DeserializeObject<SourceFileInfo[]>(embeddedSourceCode)
                .ShouldBeEquivalentTo(embeddedFiles);
            System.Text.Json.JsonSerializer.Deserialize<SourceFileInfo[]>(embeddedSourceCode)
                .ShouldBeEquivalentTo(embeddedFiles);
        }
    }
}
