using System.Threading.Tasks;

namespace SourceExpander.Generate.Config
{
    public class FIlterTest : ExpandGeneratorTestBase
    {
        [Test]
        public async Task IgnoreFile()
        {
            var test = new Test
            {
                TestState =
                {
                    AdditionalProjects =
                    {
                        ["Other"] =
                        {
                            Sources = {
                                """namespace Other{public static class C{public static void P()=>System.Console.WriteLine();}}""",
                                """
[assembly: System.Reflection.AssemblyMetadata("SourceExpander.EmbeddedSourceCode", "[{\"CodeBody\":\"namespace Other { public static class C { public static void P() => System.Console.WriteLine(); } } \",\"Dependencies\":[],\"FileName\":\"OtherDependency>C.cs\",\"TypeNames\":[\"Other.C\"],\"Usings\":[]}]")]
[assembly: System.Reflection.AssemblyMetadata("SourceExpander.EmbeddedNamespaces", "Other")]
[assembly: System.Reflection.AssemblyMetadata("SourceExpander.EmbeddedLanguageVersion","7.2")]
[assembly: System.Reflection.AssemblyMetadata("SourceExpander.EmbedderVersion","1.1.1.1")]
"""
                            }
                        },
                    },
                    AdditionalProjectReferences = { "Other" },
                    AdditionalFiles = {
                        (
                        "/foo/bar/SourceExpander.Generator.Config.json",
                        $$"""
{
    "$schema": "https://raw.githubusercontent.com/kzrnm/SourceExpander/master/schema/expander.schema.json",
    "ignore-file-pattern-regex": [ {{
            // language=regex
            @"mine/Program\d+\.cs$".ToLiteral()}} ]
}
""")
                    },
                    Sources = {
                        (
                            "/home/mine/Program.cs",
                            """
using System;
using Other;

class Program
{
    static void Main()
    {
        Console.WriteLine(42);
        C.P();
    }
}
"""
                        ),
                        (
                            "/home/mine/X/Program2.cs",
                            """
using System;
using Other;

class Program2
{
    static void M()
    {
        C.P();
    }
}
"""
                        ),
                        (
                            "/home/mine/Program1.cs",
                            """
using System;
using Other;

class Program1
{
    static void M()
    {
        C.P();
    }
}
"""
                        ),
                        (
                            "/home/mine/Program3.cs",
                            """
using System;
using Other;

class Program3
{
    static void M()
    {
        C.P();
    }
}
"""
                        ),
                    },
                    ExpectedDiagnostics =
                    {
                    },
                    GeneratedSources =
                    {
                        (typeof(ExpandGenerator), "SourceExpander.Metadata.cs",
                        EnvironmentUtil.JoinByStringBuilder(
                        "// <auto-generated/>",
                        "#pragma warning disable",
                         $$$"""[assembly: global::System.Reflection.AssemblyMetadataAttribute("SourceExpander.ExpanderVersion","{{{ExpanderVersion}}}")]"""
                         )),
                        (typeof(ExpandGenerator), "SourceExpander.Expanded.cs", $$$"""
// <auto-generated/>
#pragma warning disable
namespace SourceExpander.Expanded{
using System.Collections.Generic;
public static class ExpandedContainer{
public static IReadOnlyDictionary<string, SourceCode> Files {get{ return _Files; }}
private static Dictionary<string, SourceCode> _Files = new Dictionary<string, SourceCode>{
{"/home/mine/Program.cs",SourceCode.FromDictionary(new Dictionary<string,object>{{"path","/home/mine/Program.cs"},{"code",{{{"""
using Other;
using System;
class Program
{
    static void Main()
    {
        Console.WriteLine(42);
        C.P();
    }
}
#region Expanded by https://github.com/kzrnm/SourceExpander
namespace Other { public static class C { public static void P() => System.Console.WriteLine(); } } 
#endregion Expanded by https://github.com/kzrnm/SourceExpander
""".ReplaceEOL().ToLiteral()}}}},})},
{"/home/mine/X/Program2.cs",SourceCode.FromDictionary(new Dictionary<string,object>{{"path","/home/mine/X/Program2.cs"},{"code",{{{"""
using Other;
class Program2
{
    static void M()
    {
        C.P();
    }
}
#region Expanded by https://github.com/kzrnm/SourceExpander
namespace Other { public static class C { public static void P() => System.Console.WriteLine(); } } 
#endregion Expanded by https://github.com/kzrnm/SourceExpander
""".ReplaceEOL().ToLiteral()}}}},})},
};
}}
""".ReplaceEOL())
                    }
                }
            };
            await test.RunAsync(TestContext.Current!.Execution.CancellationToken);
        }

        [Test]
        public async Task IgnoreFileProperty()
        {
            var test = new Test
            {
                AnalyzerConfigOptions =
                {
                    {
                        "build_property.SourceExpander_Generator_IgnoreFilePatternRegex",                
                        // language=regex
                        @"mine/Program\d+\.cs$"
                    },
                },
                TestState =
                {
                    AdditionalProjects =
                    {
                        ["Other"] =
                        {
                            Sources = {
                                """namespace Other{public static class C{public static void P()=>System.Console.WriteLine();}}""",
                                 """
[assembly: System.Reflection.AssemblyMetadata("SourceExpander.EmbeddedSourceCode", "[{\"CodeBody\":\"namespace Other { public static class C { public static void P() => System.Console.WriteLine(); } } \",\"Dependencies\":[],\"FileName\":\"OtherDependency>C.cs\",\"TypeNames\":[\"Other.C\"],\"Usings\":[]}]")]
[assembly: System.Reflection.AssemblyMetadata("SourceExpander.EmbeddedNamespaces", "Other")]
[assembly: System.Reflection.AssemblyMetadata("SourceExpander.EmbeddedLanguageVersion","7.2")]
[assembly: System.Reflection.AssemblyMetadata("SourceExpander.EmbedderVersion","1.1.1.1")]
"""
                            }
                        },
                    },
                    AdditionalProjectReferences = { "Other" },
                    Sources = {
                        (
                            "/home/mine/Program.cs",
                            """
using System;
using Other;

class Program
{
    static void Main()
    {
        Console.WriteLine(42);
        C.P();
    }
}
"""
                        ),
                        (
                            "/home/mine/X/Program2.cs",
                            """
using System;
using Other;

class Program2
{
    static void M()
    {
        C.P();
    }
}
"""
                        ),
                        (
                            "/home/mine/Program1.cs",
                            """
using System;
using Other;

class Program1
{
    static void M()
    {
        C.P();
    }
}
"""
                        ),
                        (
                            "/home/mine/Program3.cs",
                            """
using System;
using Other;

class Program3
{
    static void M()
    {
        C.P();
    }
}
"""
                        ),
                    },
                    ExpectedDiagnostics =
                    {
                    },
                    GeneratedSources =
                    {
                        (typeof(ExpandGenerator), "SourceExpander.Metadata.cs",
                        EnvironmentUtil.JoinByStringBuilder(
                        "// <auto-generated/>",
                        "#pragma warning disable",
                         $$$"""[assembly: global::System.Reflection.AssemblyMetadataAttribute("SourceExpander.ExpanderVersion","{{{ExpanderVersion}}}")]"""
                         )),
                        (typeof(ExpandGenerator), "SourceExpander.Expanded.cs", $$$"""
// <auto-generated/>
#pragma warning disable
namespace SourceExpander.Expanded{
using System.Collections.Generic;
public static class ExpandedContainer{
public static IReadOnlyDictionary<string, SourceCode> Files {get{ return _Files; }}
private static Dictionary<string, SourceCode> _Files = new Dictionary<string, SourceCode>{
{"/home/mine/Program.cs",SourceCode.FromDictionary(new Dictionary<string,object>{{"path","/home/mine/Program.cs"},{"code",{{{"""
using Other;
using System;
class Program
{
    static void Main()
    {
        Console.WriteLine(42);
        C.P();
    }
}
#region Expanded by https://github.com/kzrnm/SourceExpander
namespace Other { public static class C { public static void P() => System.Console.WriteLine(); } } 
#endregion Expanded by https://github.com/kzrnm/SourceExpander
""".ReplaceEOL().ToLiteral()}}}},})},
{"/home/mine/X/Program2.cs",SourceCode.FromDictionary(new Dictionary<string,object>{{"path","/home/mine/X/Program2.cs"},{"code",{{{"""
using Other;
class Program2
{
    static void M()
    {
        C.P();
    }
}
#region Expanded by https://github.com/kzrnm/SourceExpander
namespace Other { public static class C { public static void P() => System.Console.WriteLine(); } } 
#endregion Expanded by https://github.com/kzrnm/SourceExpander
""".ReplaceEOL().ToLiteral()}}}},})},
};
}}
""".ReplaceEOL())
                    }
                }
            };
            await test.RunAsync(TestContext.Current!.Execution.CancellationToken);
        }

        [Test]
        public async Task Whitelist()
        {            
            var test = new Test
            {
                TestState =
                {
                    AdditionalProjects =
                    {
                        ["Other"] =
                        {
                            Sources = {
                                """namespace Other{public static class C{public static void P()=>System.Console.WriteLine();}}""",
                                """
[assembly: System.Reflection.AssemblyMetadata("SourceExpander.EmbeddedSourceCode", "[{\"CodeBody\":\"namespace Other { public static class C { public static void P() => System.Console.WriteLine(); } } \",\"Dependencies\":[],\"FileName\":\"OtherDependency>C.cs\",\"TypeNames\":[\"Other.C\"],\"Usings\":[]}]")]
[assembly: System.Reflection.AssemblyMetadata("SourceExpander.EmbeddedNamespaces", "Other")]
[assembly: System.Reflection.AssemblyMetadata("SourceExpander.EmbeddedLanguageVersion","7.2")]
[assembly: System.Reflection.AssemblyMetadata("SourceExpander.EmbedderVersion","1.1.1.1")]
"""
                            }
                        },
                    },
                    AdditionalProjectReferences = { "Other" },
                    AdditionalFiles = {
                    (
                    "/foo/bar/SourceExpander.Generator.Config.json",
                    $$"""
                    {
                        "$schema": "https://raw.githubusercontent.com/kzrnm/SourceExpander/master/schema/expander.schema.json",
                        "match-file-pattern": [ {{"mine/Program.cs".ToLiteral()}} ]
                    }
                    """)
                    },
                    Sources = {
                        (
                            "/home/mine/Program.cs",
                            """
using System;
using Other;

class Program
{
    static void Main()
    {
        Console.WriteLine(42);
        C.P();
    }
}
"""
                        ),
                        (
                            "/home/mine/Program2.cs",
                            """
using System;
using Other;

class Program2
{
    static void M()
    {
        C.P();
    }
}
"""
                        ),
                    },
                    ExpectedDiagnostics =
                    {
                    },
                    GeneratedSources =
                    {
                        (typeof(ExpandGenerator), "SourceExpander.Metadata.cs",
                        EnvironmentUtil.JoinByStringBuilder(
                        "// <auto-generated/>",
                        "#pragma warning disable",
                         $$$"""[assembly: global::System.Reflection.AssemblyMetadataAttribute("SourceExpander.ExpanderVersion","{{{ExpanderVersion}}}")]"""
                         )),
                        (typeof(ExpandGenerator), "SourceExpander.Expanded.cs", $$$"""
// <auto-generated/>
#pragma warning disable
namespace SourceExpander.Expanded{
using System.Collections.Generic;
public static class ExpandedContainer{
public static IReadOnlyDictionary<string, SourceCode> Files {get{ return _Files; }}
private static Dictionary<string, SourceCode> _Files = new Dictionary<string, SourceCode>{
{"/home/mine/Program.cs",SourceCode.FromDictionary(new Dictionary<string,object>{{"path","/home/mine/Program.cs"},{"code",{{{"""
using Other;
using System;
class Program
{
    static void Main()
    {
        Console.WriteLine(42);
        C.P();
    }
}
#region Expanded by https://github.com/kzrnm/SourceExpander
namespace Other { public static class C { public static void P() => System.Console.WriteLine(); } } 
#endregion Expanded by https://github.com/kzrnm/SourceExpander
""".ReplaceEOL().ToLiteral()}}}},})},
};
}}
""".ReplaceEOL())
                    }
                }
            };
            await test.RunAsync(TestContext.Current!.Execution.CancellationToken);
        }

        [Test]
        public async Task WhitelistProperty()
        {
            var test = new Test
            {
                AnalyzerConfigOptions =
                {
                    { "build_property.SourceExpander_Generator_MatchFilePattern", "mine/Program.cs" },
                },
                TestState =
                {
                    AdditionalProjects =
                    {
                        ["Other"] =
                        {
                            Sources = {
                                """namespace Other{public static class C{public static void P()=>System.Console.WriteLine();}}""",
                                """
[assembly: System.Reflection.AssemblyMetadata("SourceExpander.EmbeddedSourceCode", "[{\"CodeBody\":\"namespace Other { public static class C { public static void P() => System.Console.WriteLine(); } } \",\"Dependencies\":[],\"FileName\":\"OtherDependency>C.cs\",\"TypeNames\":[\"Other.C\"],\"Usings\":[]}]")]
[assembly: System.Reflection.AssemblyMetadata("SourceExpander.EmbeddedNamespaces", "Other")]
[assembly: System.Reflection.AssemblyMetadata("SourceExpander.EmbeddedLanguageVersion","7.2")]
[assembly: System.Reflection.AssemblyMetadata("SourceExpander.EmbedderVersion","1.1.1.1")]
"""
                            }
                        },
                    },
                    AdditionalProjectReferences = { "Other" },
                    Sources = {
                        (
                            "/home/mine/Program.cs",
                            """
using System;
using Other;

class Program
{
    static void Main()
    {
        Console.WriteLine(42);
        C.P();
    }
}
"""
                        ),
                        (
                            "/home/mine/Program2.cs",
                            """
using System;
using Other;

class Program2
{
    static void M()
    {
        C.P();
    }
}
"""
                        ),
                    },
                    ExpectedDiagnostics =
                    {
                    },
                    GeneratedSources =
                    {
                        (typeof(ExpandGenerator), "SourceExpander.Metadata.cs",
                        EnvironmentUtil.JoinByStringBuilder(
                        "// <auto-generated/>",
                        "#pragma warning disable",
                         $$$"""[assembly: global::System.Reflection.AssemblyMetadataAttribute("SourceExpander.ExpanderVersion","{{{ExpanderVersion}}}")]"""
                         )),
                        (typeof(ExpandGenerator), "SourceExpander.Expanded.cs", $$$"""
// <auto-generated/>
#pragma warning disable
namespace SourceExpander.Expanded{
using System.Collections.Generic;
public static class ExpandedContainer{
public static IReadOnlyDictionary<string, SourceCode> Files {get{ return _Files; }}
private static Dictionary<string, SourceCode> _Files = new Dictionary<string, SourceCode>{
{"/home/mine/Program.cs",SourceCode.FromDictionary(new Dictionary<string,object>{{"path","/home/mine/Program.cs"},{"code",{{{"""
using Other;
using System;
class Program
{
    static void Main()
    {
        Console.WriteLine(42);
        C.P();
    }
}
#region Expanded by https://github.com/kzrnm/SourceExpander
namespace Other { public static class C { public static void P() => System.Console.WriteLine(); } } 
#endregion Expanded by https://github.com/kzrnm/SourceExpander
""".ReplaceEOL().ToLiteral()}}}},})},
};
}}
""".ReplaceEOL())
                    }
                }
            };
            await test.RunAsync(TestContext.Current!.Execution.CancellationToken);
        }
    }
}
