using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using SourceExpander.Roslyn;

namespace SourceExpander;

public partial class ExpandGenerator
{
    private const string CONFIG_FILE_NAME = "SourceExpander.Generator.Config.json";
    private const string EMBEDDED_FILE_NAME = "SourceExpander.Embedded.json";
    internal void Execute(
        IContextWrappter ctx,
        CSharpCompilation compilation,
        CSharpParseOptions parseOptions,
        AnalyzerConfigOptions analyzerConfigOptions,
        ImmutableArray<AdditionalText> embeddedDataJsons,
        ExpandConfig.Builder configBuilder)
    {
        try
        {
            var config = ParseConfigWithDiagnostic(ctx, configBuilder, analyzerConfigOptions);

            if (!config.Enabled)
                return;
            if (parseOptions is { LanguageVersion: <= LanguageVersion.CSharp3 })
                return;

            var embeddedDataBuilder = ImmutableArray.CreateBuilder<EmbeddedData>();
            foreach (var additionalText in embeddedDataJsons)
                if (additionalText.GetText(ctx.CancellationToken) is { } sourceText)
                {
                    try
                    {
                        var obj = JsonUtil.ParseJson<EmbeddedData>(sourceText);
                        if (obj is not null)
                            embeddedDataBuilder.Add(obj);
                    }
                    catch (ParseJsonException)
                    {
                        ctx.ReportDiagnostic(DiagnosticDescriptors.EXPAND0011_InvalidEmbeddedData(additionalText.Path));
                    }
                }

            ctx.CancellationToken.ThrowIfCancellationRequested();
            var loader = new EmbeddedLoaderWithDiagnostic(
                compilation,
                parseOptions,
                embeddedDataBuilder.ToImmutable(),
                ctx, config, ctx.CancellationToken);
            if (loader.IsEmbeddedEmpty)
                ctx.ReportDiagnostic(DiagnosticDescriptors.EXPAND0003_NotFoundEmbedded());

            var metadata = new List<(string name, string code)>();
            if (config.MetadataExpandingFile is { Length: > 0 } metadataExpandingFile)
            {
                try
                {
                    var (_, code) = loader.ExpandedCodes()
                       .First(rt => rt.SyntaxTree.FilePath.IndexOf(metadataExpandingFile, StringComparison.OrdinalIgnoreCase) >= 0);

                    metadata.Add(("SourceExpander.Expanded.Default", code));
                }
                catch (InvalidOperationException)
                {
                    ctx.ReportDiagnostic(DiagnosticDescriptors.EXPAND0009_MetadataEmbeddingFileNotFound(metadataExpandingFile));
                }
            }
            metadata.Add(("SourceExpander.ExpanderVersion", AssemblyUtil.AssemblyVersion.ToString()));
            ctx.AddSource("SourceExpander.Metadata.cs", CreateMetadataSource(metadata));


            if (config.ExpandingAll)
            {
                ctx.CancellationToken.ThrowIfCancellationRequested();
                ctx.AddSource("SourceExpander.ExpandingAll.cs", loader.ExpandAllForTesting(ctx.CancellationToken));
            }

            var expandedCodes = loader.ExpandedCodes();
            ctx.CancellationToken.ThrowIfCancellationRequested();

            var expanded = CreateExpanded(expandedCodes);
            ctx.CancellationToken.ThrowIfCancellationRequested();
            ctx.AddSource("SourceExpander.Expanded.cs", expanded);

            if (!compilation.Options.AllowUnsafe)
            {
                foreach (var (tree, code) in expandedCodes)
                {
                    if (code == null) continue;

                    var expandedTree = CSharpSyntaxTree.ParseText(code, parseOptions, cancellationToken: ctx.CancellationToken);
                    var root = expandedTree.GetRoot(ctx.CancellationToken);
                    if (root.DescendantTokens().Any(t => t.IsKind(SyntaxKind.UnsafeKeyword)))
                    {
                        ctx.ReportDiagnostic(DiagnosticDescriptors.EXPAND0010_UnsafeBlock(tree.FilePath));
                    }
                }
            }
        }
        catch (OperationCanceledException)
        {
            Trace.WriteLine(nameof(ExpandGenerator) + "." + nameof(Execute) + "is Canceled.");
        }
        catch (Exception e)
        {
            Trace.WriteLine(e.ToString());
            ctx.ReportDiagnostic(
                DiagnosticDescriptors.EXPAND0001_UnknownError(e.Message));
        }
    }

    static SourceText CreateExpanded(IEnumerable<ExpandedResult> expanded)
    {

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("namespace SourceExpander.Expanded{");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("public static class ExpandedContainer{");
        sb.AppendLine("public static IReadOnlyDictionary<string, SourceCode> Files {get{ return _Files; }}");
        sb.AppendLine("private static Dictionary<string, SourceCode> _Files = new Dictionary<string, SourceCode>{");

        static void CreateSourceCodeLiteral(StringBuilder sb, string pathLiteral, string codeLiteral)
            => sb.Append("SourceCode.FromDictionary(new Dictionary<string,object>{")
              .AppendDicElement("\"path\"", pathLiteral)
              .AppendDicElement("\"code\"", codeLiteral)
              .Append("})");

        foreach (var (tree, code) in expanded)
        {
            var filePathLiteral = tree.FilePath.ToLiteral();
            sb.AppendDicElement(filePathLiteral, sb => CreateSourceCodeLiteral(sb, filePathLiteral, code.ToLiteral()));
            sb.AppendLine();
        }
        sb.AppendLine("};");
        sb.AppendLine("}}");
        return SourceText.From(sb.ToString(), Encoding.UTF8);
    }

    static SourceText CreateMetadataSource(IEnumerable<(string Key, string Value)> metadatas)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable");
        foreach (var (key, value) in metadatas)
        {
            sb.Append("[assembly: global::System.Reflection.AssemblyMetadataAttribute(")
              .Append(key.ToLiteral()).Append(",")
              .Append(value.ToLiteral())
              .AppendLine(")]");
        }
        return SourceText.From(sb.ToString(), Encoding.UTF8);
    }

    internal static ExpandConfig ParseConfigWithDiagnostic(IContextWrappter ctx, ExpandConfig.Builder builder, AnalyzerConfigOptions analyzerConfigOptions)
    {
        var isDesignTimeBuild = StringComparer.OrdinalIgnoreCase.Equals(
            analyzerConfigOptions.GetOrNull("build_property.DesignTimeBuild"),
            "true");
        if (isDesignTimeBuild)
            return new ExpandConfig(false);

        ctx.CancellationToken.ThrowIfCancellationRequested();
        try
        {
            var config = builder.Build(ctx.CancellationToken);
            return config;
        }
        catch (ParseJsonException e)
        {
            ctx.ReportDiagnostic(DiagnosticDescriptors.EXPAND0007_ParseConfigError(builder.SourceText?.Path, e.Message));
            return new ExpandConfig(); ;
        }
    }
}
