using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace SourceExpander.Embedder.Syntaxes;

public abstract class SyntaxKindTestBase : EmbedderGeneratorTestBase
{
    public abstract string Syntax { get; }
    public abstract IEnumerable<string> ExpectedTypeNames { get; }
    public abstract IEnumerable<string> ExpectedUsings { get; }
    public abstract IEnumerable<string> ExpectedDependencies { get; }
    public abstract string ExpectedCodeBody { get; }
    public abstract string ExpectedMinifyCodeBody { get; }
    public abstract IEnumerable<string> ExpectedNamespaces { get; }
    public InMemorySourceText Source => new("/foo/path.cs", Syntax);
    internal SourceFileInfo Expected => new(
                "TestProject>path.cs",
                ExpectedTypeNames,
                ExpectedUsings,
                ExpectedDependencies,
                ExpectedCodeBody);
    internal SourceFileInfo ExpectedMinify => new(
                "TestProject>path.cs",
                ExpectedTypeNames,
                ExpectedUsings,
                ExpectedDependencies,
                ExpectedMinifyCodeBody);
    public string ExpectedJson => JsonUtil.ToJson(new[] { Expected });
    public string ExpectedMinifyJson => JsonUtil.ToJson(new[] { ExpectedMinify });

    [Test]
    public async Task Generate(CancellationToken cancellationToken)
    {
        var test = new Test
        {
            CompilationOptions = new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, allowUnsafe: true),
            TestState =
            {
                AdditionalFiles =
                {
                    (
        "/foo/bar/SourceExpander.Embedder.Config.json", """
{
    "$schema": "https://raw.githubusercontent.com/kzrnm/SourceExpander/master/schema/embedder.schema.json",
    "embedding-type": "Raw"
}
"""),
                },
                Sources =
                {
                    Source,
                },
                GeneratedSources =
                {
                    (typeof(EmbedderGenerator), "EmbeddedSourceCode.Metadata.cs",
                    EnvironmentUtil.JoinByStringBuilder(
                    "// <auto-generated/>",
                    "#pragma warning disable",
                    "[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"SourceExpander.EmbeddedAllowUnsafe\",\"true\")]",
                    $"[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"SourceExpander.EmbedderVersion\",\"{EmbedderVersion}\")]",
                    $"[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"SourceExpander.EmbeddedLanguageVersion\",\"{EmbeddedLanguageVersion}\")]",
                    $"[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"SourceExpander.EmbeddedNamespaces\",\"{string.Join(",", ExpectedNamespaces)}\")]",
                    $"[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"SourceExpander.EmbeddedSourceCode\",{ExpectedJson.ToLiteral()})]")
                    ),
                },
            }
        };
        await test.RunAsync(cancellationToken);
        await Newtonsoft.Json.JsonConvert.DeserializeObject<SourceFileInfo[]>(ExpectedJson)
            .Should()
            .BeEquivalentTo([Expected], TestUtil.SourceFileInfoEqualityComparer);
        await System.Text.Json.JsonSerializer.Deserialize<SourceFileInfo[]>(ExpectedJson)
            .Should()
            .BeEquivalentTo([Expected], TestUtil.SourceFileInfoEqualityComparer);
    }

    [Test]
    public async Task Minify(CancellationToken cancellationToken)
    {
        var test = new Test
        {
            CompilationOptions = new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, allowUnsafe: true),
            TestState =
            {
                AdditionalFiles =
                {
                    (
        "/foo/bar/SourceExpander.Embedder.Config.json", """
{
    "$schema": "https://raw.githubusercontent.com/kzrnm/SourceExpander/master/schema/embedder.schema.json",
    "embedding-type": "Raw",
    "minify-level": "full"
}
"""),
                },
                Sources =
                {
                    Source,
                },
                GeneratedSources =
                {
                    (typeof(EmbedderGenerator), "EmbeddedSourceCode.Metadata.cs",
                    EnvironmentUtil.JoinByStringBuilder(
                    "// <auto-generated/>",
                    "#pragma warning disable",
                    "[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"SourceExpander.EmbeddedAllowUnsafe\",\"true\")]",
                    $"[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"SourceExpander.EmbedderVersion\",\"{EmbedderVersion}\")]",
                    $"[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"SourceExpander.EmbeddedLanguageVersion\",\"{EmbeddedLanguageVersion}\")]",
                    $"[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"SourceExpander.EmbeddedNamespaces\",\"{string.Join(",", ExpectedNamespaces)}\")]",
                    $"[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"SourceExpander.EmbeddedSourceCode\",{ExpectedMinifyJson.ToLiteral()})]")
                    ),
                },
            }
        };
        await test.RunAsync(cancellationToken);
        await Newtonsoft.Json.JsonConvert.DeserializeObject<SourceFileInfo[]>(ExpectedMinifyJson)
            .Should()
            .BeEquivalentTo([ExpectedMinify], TestUtil.SourceFileInfoEqualityComparer);
        await System.Text.Json.JsonSerializer.Deserialize<SourceFileInfo[]>(ExpectedMinifyJson)
            .Should()
            .BeEquivalentTo([ExpectedMinify], TestUtil.SourceFileInfoEqualityComparer);
    }
}
