using System.Diagnostics.CodeAnalysis;
using Microsoft.CodeAnalysis;

namespace SourceExpander;

public class EmbedderGeneratorTestBase : GeneratorTestBase<EmbedderGenerator>
{
    public class Test : TestBase
    {
        public Test()
        {
            AnalyzerConfigOptions.Add(
                typeof(EmbedderConfig.Builder).GetProperties()
                    .Where(p => p.Name is not "SourceText")
                    .Select(p => KeyValuePair.Create($"build_property.SourceExpander_Embedder_{p.Name}", "")));
            foreach (var (hintName, sourceText) in Constants.CompileTimeSources)
            {
                TestState.GeneratedSources.Add((typeof(EmbedderGenerator), hintName, sourceText));
            }
        }

        public Test(
            [StringSyntax("C#")] string embeddedSourceCode,
            IEnumerable<string> embeddedNamespaces = null) : this()
        {
            TestState.GeneratedSources.Add(
                    (typeof(EmbedderGenerator), "EmbeddedSourceCode.Metadata.cs",
                    EnvironmentUtil.JoinByStringBuilder(
                    "// <auto-generated/>",
                    "#pragma warning disable",
                    "[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"SourceExpander.EmbeddedAllowUnsafe\",\"true\")]",
                    $"[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"SourceExpander.EmbedderVersion\",\"{EmbedderVersion}\")]",
                    $"[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"SourceExpander.EmbeddedLanguageVersion\",\"{EmbeddedLanguageVersion}\")]",
                    $"[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"SourceExpander.EmbeddedNamespaces\",\"{string.Join(",", embeddedNamespaces ?? [])}\")]",
                    $"[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"SourceExpander.EmbeddedSourceCode\",{embeddedSourceCode.ToLiteral()})]")
                    ));
        }
    }

    public static string EmbedderVersion => typeof(EmbedderGenerator).Assembly.GetName().Version.ToString();
    public static string EmbeddedLanguageVersion => "preview";

    public static InMemorySourceText enableMinifyJson = new(
        "/foo/bar/SourceExpander.Embedder.Config.json", """
{
    "$schema": "https://raw.githubusercontent.com/kzrnm/SourceExpander/master/schema/embedder.schema.json",
    "embedding-type": "Raw",
    "minify-level": "full"
}
""");
}
