using System.Diagnostics.CodeAnalysis;
using Microsoft.CodeAnalysis;

namespace SourceExpander;

public class EmbedderGeneratorTestBase : GeneratorTestBase<EmbedderGenerator>
{
    public class Test : TestBase
    {
        public Test()
        {
            AnalyzerConfigOptions.Add(
                typeof(EmbedderConfig.Builder).GetProperties()
                    .Where(p => p.Name is not "SourceText")
                    .Select(p => KeyValuePair.Create($"build_property.SourceExpander_Embedder_{p.Name}", "")));
            foreach (var (hintName, sourceText) in Constants.CompileTimeSources)
            {
                TestState.GeneratedSources.Add((typeof(EmbedderGenerator), hintName, sourceText));
            }
        }

        public Test(TestParams p) : this()
        {
            List<string> metadata = [
                "// <auto-generated/>",
                "#pragma warning disable",
            ];

            if (p.AllowUnsafe)
                metadata.Add(AssemblyMetadataAttribute("SourceExpander.EmbeddedAllowUnsafe", "true"));
            metadata.AddRange(
                AssemblyMetadataAttribute("SourceExpander.EmbedderVersion", p.EmbedderVersion ?? EmbedderVersion),
                AssemblyMetadataAttribute("SourceExpander.EmbeddedLanguageVersion", p.EmbeddedLanguageVersion ?? EmbeddedLanguageVersion),
                AssemblyMetadataAttribute("SourceExpander.EmbeddedNamespaces", string.Join(",", p.EmbeddedNamespaces ?? [])),
                AssemblyMetadataAttribute("SourceExpander.EmbeddedSourceCode", p.EmbeddedSourceCode));

            TestState.GeneratedSources.Add(
                (typeof(EmbedderGenerator), "EmbeddedSourceCode.Metadata.cs", EnvironmentUtil.JoinByStringBuilder(metadata))
            );
            static string AssemblyMetadataAttribute(string key, string value)
                => $"[assembly: global::System.Reflection.AssemblyMetadataAttribute({key.ToLiteral()},{value.ToLiteral()})]";
        }
    }

    public record TestParams(
        bool AllowUnsafe = false,
        string EmbedderVersion = null,
        string EmbeddedLanguageVersion = null,
        IEnumerable<string> EmbeddedNamespaces = null,
        [property: StringSyntax("json")][param: StringSyntax("json")] string EmbeddedSourceCode = null);

    public static string EmbedderVersion => typeof(EmbedderGenerator).Assembly.GetName().Version.ToString();
    public static string EmbeddedLanguageVersion => "preview";

    public static InMemorySourceText enableMinifyJson = new(
        "/foo/bar/SourceExpander.Embedder.Config.json", """
{
    "$schema": "https://raw.githubusercontent.com/kzrnm/SourceExpander/master/schema/embedder.schema.json",
    "embedding-type": "Raw",
    "minify-level": "full"
}
""");
}
