using System.Diagnostics.CodeAnalysis;
using Microsoft.CodeAnalysis;

namespace SourceExpander;

public class EmbedderGeneratorTestBase : GeneratorTestBase<EmbedderGenerator>
{
    public class Test : TestBase
    {
        public Test()
        {
            AnalyzerConfigOptions.Add(
                typeof(EmbedderConfig.Builder).GetProperties()
                    .Where(p => p.Name is not "SourceText")
                    .Select(p => KeyValuePair.Create($"build_property.SourceExpander_Embedder_{p.Name}", "")));
            foreach (var (hintName, sourceText) in Constants.CompileTimeSources)
            {
                TestState.GeneratedSources.Add((typeof(EmbedderGenerator), hintName, sourceText));
            }
        }

        public Test(TestParams p) : this()
        {
            List<string> metadata = [
                "// <auto-generated/>",
                "#pragma warning disable",
            ];

            foreach (var (k, v) in EnumerateMetadata(p))
                metadata.Add(AssemblyMetadataAttribute(k, v));

            TestState.GeneratedSources.Add(
                (typeof(EmbedderGenerator), "EmbeddedSourceCode.Metadata.cs", EnvironmentUtil.JoinByStringBuilder(metadata))
            );

            static IEnumerable<KeyValuePair<string, string>> EnumerateMetadata(TestParams p)
            {
                yield return new("SourceExpander.EmbedderVersion", p.EmbedderVersion ?? EmbedderVersion);
                if (p.AllowUnsafe)
                    yield return new("SourceExpander.EmbeddedAllowUnsafe", "true");
                yield return new("SourceExpander.EmbeddedLanguageVersion", p.EmbeddedLanguageVersion ?? EmbeddedLanguageVersion);
                yield return new("SourceExpander.EmbeddedNamespaces", p.EmbeddedNamespaces ?? "");

                if (p.EmbeddedSourceCode is not null)
                    yield return new("SourceExpander.EmbeddedSourceCode", p.EmbeddedSourceCode);
                if (p.EmbeddedSourceCodeGZip is not null)
                    yield return new("SourceExpander.EmbeddedSourceCode.GZipBase32768", SourceFileInfoUtil.ToGZipBase32768(p.EmbeddedSourceCodeGZip));
            }
        }
    }

    public record TestParams(
        string EmbedderVersion = null,
        string EmbeddedLanguageVersion = null,
        string EmbeddedNamespaces = null,
        [property: StringSyntax("json")][param: StringSyntax("json")] string EmbeddedSourceCode = null,
        string EmbeddedSourceCodeGZip = null,
        bool AllowUnsafe = false);

    public static string EmbedderVersion => typeof(EmbedderGenerator).Assembly.GetName().Version.ToString();
    public static string EmbeddedLanguageVersion => "preview";

    public static string AssemblyMetadataAttribute(string key, string value)
        => $"[assembly: global::System.Reflection.AssemblyMetadataAttribute({key.ToLiteral()},{value.ToLiteral()})]";

    public static InMemorySourceText enableMinifyJson = new(
        "/foo/bar/SourceExpander.Embedder.Config.json", """
{
    "$schema": "https://raw.githubusercontent.com/kzrnm/SourceExpander/master/schema/embedder.schema.json",
    "embedding-type": "Raw",
    "minify-level": "full"
}
""");
}
