namespace SourceExpander.Generate;

public class EmbederJsonTest : ExpandGeneratorTestBase
{
    [Test]
    public async Task Generate(CancellationToken cancellationToken)
    {
        var test = new Test
        {
            TestState =
            {
                AdditionalFiles =
                {
                    ("OtherSourceExpander.Embedded.json",
                    // lang=json
                    """
                    {
                        "AssemblyName": "override",
                        "Sources": [
                            {
                                "CodeBody": "namespace Other { public static partial class C{ public static int Add(int a, int b)=>a+b;}}",
                                "Dependencies": [],
                                "FileName": "override>Other.cs",
                                "TypeNames": [
                                    "Other.C"
                                ],
                                "Usings": []
                            }
                        ],
                        "EmbedderVersion": "1.0.0",
                        "CSharpVersion": "8",
                        "AllowUnsafe": false,
                        "EmbeddedNamespaces": [
                            "Other"
                        ]
                    }
                    """)
                },
                AdditionalProjects =
                {
                    ["Other"] =
                    {
                        Sources = {
                            """namespace Other{public static partial class C{public static void P()=>System.Console.WriteLine();}}""",
                            """
[assembly: System.Reflection.AssemblyMetadata("SourceExpander.EmbeddedSourceCode", "[{\"CodeBody\":\"namespace Other { public static partial class C { public static void P() => System.Console.WriteLine(); } } \",\"Dependencies\":[],\"FileName\":\"OtherDependency>C.cs\",\"TypeNames\":[\"Other.C\"],\"Usings\":[]}]")]
[assembly: System.Reflection.AssemblyMetadata("SourceExpander.EmbeddedNamespaces", "Other")]
[assembly: System.Reflection.AssemblyMetadata("SourceExpander.EmbeddedLanguageVersion","7.2")]
[assembly: System.Reflection.AssemblyMetadata("SourceExpander.EmbedderVersion","2.3.4.5")]
"""
                        }
                    },
                },
                AdditionalProjectReferences = { "Other" },
                Sources = {
                    (
                        "/home/mine/Program.cs",
                        """
using System;
using Other;

class Program
{
    static void Main()
    {
        Console.WriteLine(42);
        C.P();
    }
}
"""
                    ),
                },
                GeneratedSources =
                {
                    (typeof(ExpandGenerator), "SourceExpander.Metadata.cs",
                    EnvironmentUtil.JoinByStringBuilder(
                    "// <auto-generated/>",
                    "#pragma warning disable",
                     $$$"""[assembly: global::System.Reflection.AssemblyMetadataAttribute("SourceExpander.ExpanderVersion","{{{ExpanderVersion}}}")]"""
                     )),
                    (typeof(ExpandGenerator), "SourceExpander.Expanded.cs", $$$"""
// <auto-generated/>
#pragma warning disable
namespace SourceExpander.Expanded{
using System.Collections.Generic;
public static class ExpandedContainer{
public static IReadOnlyDictionary<string, SourceCode> Files {get{ return _Files; }}
private static Dictionary<string, SourceCode> _Files = new Dictionary<string, SourceCode>{
{"/home/mine/Program.cs",SourceCode.FromDictionary(new Dictionary<string,object>{{"path","/home/mine/Program.cs"},{"code",{{{"""
using Other;
using System;
class Program
{
    static void Main()
    {
        Console.WriteLine(42);
        C.P();
    }
}
#region Expanded by https://github.com/kzrnm/SourceExpander
namespace Other { public static partial class C { public static void P() => System.Console.WriteLine(); } } 
namespace Other { public static partial class C{ public static int Add(int a, int b)=>a+b;}}
#endregion Expanded by https://github.com/kzrnm/SourceExpander
""".ReplaceEOL().ToLiteral()}}}},})},
};
}}
""".ReplaceEOL())
                }
            }
        };
        await test.RunAsync(cancellationToken);
    }
}
