using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace SourceExpander
{
    public static class CompileTimeTypeMaker
    {
        public static readonly ImmutableArray<(string hintName, SourceText sourceText)> Sources
            = ImmutableArray.Create<(string hintName, SourceText sourceText)>(
                ("NotEmbeddingSourceAttribute.cs", NotEmbeddingText)
            );
        public static int SourceCount => Sources.Length;

        private static SourceText NotEmbeddingText => SourceText.From("""
// <auto-generated/>
#pragma warning disable
namespace SourceExpander
{
    [global::System.AttributeUsage(global::System.AttributeTargets.All, Inherited = false, AllowMultiple = true)]
    [global::System.Diagnostics.Conditional("COMPILE_TIME_ONLY")]
    [NotEmbeddingSource]
    internal sealed class NotEmbeddingSourceAttribute : global::System.Attribute
    {
        public NotEmbeddingSourceAttribute() { }
    }
}
""", Encoding.UTF8);
    }
}
