using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis.Text;


namespace SourceExpander
{
    public static class Constants
    {
        public static readonly ImmutableArray<(string hintName, SourceText sourceText)> CompileTimeSources
            = ImmutableArray.Create<(string hintName, SourceText sourceText)>(
                ("SourceExpanderAttributes.cs", Attributes)
            );
        public static int SourceCount => CompileTimeSources.Length;

        private static SourceText Attributes => SourceText.From(
            // lang=c#
            """
// <auto-generated/>
#pragma warning disable
namespace SourceExpander
{
    [global::System.AttributeUsage(global::System.AttributeTargets.All, Inherited = false, AllowMultiple = true)]
    [global::System.Diagnostics.Conditional("COMPILE_TIME_ONLY")]
    [NotEmbeddingSource]
    internal sealed class NotEmbeddingSourceAttribute : global::System.Attribute
    {
        public NotEmbeddingSourceAttribute() { }
    }
}
""", Encoding.UTF8);
    }
}
