using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using SourceExpander.Roslyn;

namespace SourceExpander;

[Generator]
public class EmbedderGenerator : IIncrementalGenerator
{
    private const string CONFIG_FILE_NAME = "SourceExpander.Embedder.Config.json";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            foreach (var (hintName, sourceText) in Constants.CompileTimeSources)
                ctx.AddSource(hintName, sourceText);
        });

        var configProvider
            = context.AdditionalTextsProvider
            .Where(a => StringComparer.OrdinalIgnoreCase.Compare(Path.GetFileName(a.Path), CONFIG_FILE_NAME) == 0)
            .Collect()
            .Select((ats, _) => ats.FirstOrDefault())
            .Combine(context.AnalyzerConfigOptionsProvider.Select((s, _) => s.GlobalOptions))
            .Select((tup, ct) => (tup.Right, EmbedderConfig.LoadBuilder(tup.Left, tup.Right)));

        var source = context.CompilationProvider
            .Combine(context.ParseOptionsProvider)
            .Combine(configProvider);

        context.RegisterImplementationSourceOutput(source, (ctx, source) =>
        {
            var ((compilation, parseOptions), (analyzerConfigOptions, configBuilder)) = source;
            Execute(
                new SourceProductionContextWrappter(ctx),
                (CSharpCompilation)compilation,
                (CSharpParseOptions)parseOptions,
                analyzerConfigOptions,
                configBuilder);
        });
    }

    internal void Execute(IContextWrappter ctx, CSharpCompilation compilation, CSharpParseOptions parseOptions, AnalyzerConfigOptions analyzerConfigOptions, EmbedderConfig.Builder configBuilder)
    {
        try
        {
            var config = ParseConfigWithDiagnostic(ctx, configBuilder, analyzerConfigOptions);

            if (!compilation.SyntaxTrees.Any()) return;
            if (!config.Enabled)
                return;

            const string SOURCE_EMBEDDING = nameof(SOURCE_EMBEDDING);
            parseOptions = parseOptions.WithPreprocessorSymbols(parseOptions.PreprocessorSymbolNames.Concat([SOURCE_EMBEDDING]));

            foreach (var tree in compilation.SyntaxTrees)
            {
                var root = (CSharpSyntaxNode)tree.GetRoot(ctx.CancellationToken);
                if (new IfDirectiveWalker().VisitRoot(root))
                {
                    var newTree = CSharpSyntaxTree.ParseText(root.ToFullString(), parseOptions, tree.FilePath, tree.Encoding, ctx.CancellationToken);
                    compilation = compilation.ReplaceSyntaxTree(tree, newTree);
                }
            }

            var resolver = new EmbeddingResolver(
                compilation,
                parseOptions,
                ctx,
                config,
                ctx.CancellationToken);
            var resolvedSources = resolver.ResolveFiles();

            if (resolvedSources.Length == 0)
                return;

            ctx.AddSource(
                "EmbeddedSourceCode.Metadata.cs", CreateMetadataSource(resolver.EnumerateAssemblyMetadata()));

            if (config.EmbeddingSourceClassName != null)
                ctx.AddSource(
                    "EmbeddingSourceClass.cs",
                    CreateEmbbedingSourceClass(resolvedSources, config.EmbeddingSourceClassName));

            if (config.ExpandInLibrary)
                ctx.AddSource("ExpandInLibrary.cs", ExpandInLibrary(resolvedSources));

        }
        catch (OperationCanceledException)
        {
            Trace.WriteLine(nameof(EmbedderGenerator) + "." + nameof(Execute) + "is Canceled.");
        }
        catch (Exception e)
        {
            Trace.WriteLine(e.ToString());
            ctx.ReportDiagnostic(
                DiagnosticDescriptors.EMBED0001_UnknownError(e.Message));
        }
    }

    static SourceText CreateMetadataSource(IEnumerable<(string Key, string Value)> metadatas)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable");
        foreach (var (key, value) in metadatas)
        {
            sb.Append("[assembly: global::System.Reflection.AssemblyMetadataAttribute(")
              .Append(key.ToLiteral()).Append(",")
              .Append(value.ToLiteral())
              .AppendLine(")]");
        }
        return SourceText.From(sb.ToString(), Encoding.UTF8);
    }

    static SourceText CreateEmbbedingSourceClass(
        ImmutableArray<SourceFileInfo> sources,
        string className)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable");

        sb.AppendLine("namespace SourceExpander.Embedded{");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("public class " + className + "{");
        sb.AppendLine("public class SourceFileInfo{");
        sb.AppendLine("  public string FileName{get;set;}");
        sb.AppendLine("  public string[] TypeNames{get;set;}");
        sb.AppendLine("  public string[] Usings{get;set;}");
        sb.AppendLine("  public string[] Dependencies{get;set;}");
        sb.AppendLine("  public string CodeBody{get;set;}");
        sb.AppendLine("}");
        sb.AppendLine("  public static readonly IReadOnlyList<SourceFileInfo> Files = new SourceFileInfo[]{");
        foreach (var source in sources)
        {
            sb.AppendLine("    new SourceFileInfo{");
            if (source.FileName is { } fileName)
                sb.Append("      FileName = ").Append(fileName.ToLiteral()).AppendLine(",");
            if (source.CodeBody is { } body)
                sb.Append("      CodeBody = ").Append(body.ToLiteral()).AppendLine(",");
            if (source.TypeNames is { } typeNames)
            {
                sb.AppendLine("      TypeNames = new string[]{");
                foreach (var ty in typeNames.Select(s => s.ToLiteral()))
                    sb.Append("        ").Append(ty).AppendLine(",");
                sb.AppendLine("      },");
            }
            if (source.Usings is { } usings)
            {
                sb.AppendLine("      Usings = new string[]{");
                foreach (var u in usings.OrderBy(s => s).Select(s => s.ToLiteral()))
                    sb.Append("        ").Append(u).AppendLine(",");
                sb.AppendLine("      },");
            }
            if (source.Dependencies is { } deps)
            {
                sb.AppendLine("      Dependencies = new string[]{");
                foreach (var d in deps.Select(s => s.ToLiteral()))
                    sb.Append("        ").Append(d).AppendLine(",");
                sb.AppendLine("      },");
            }
            sb.AppendLine("    },");
        }
        sb.AppendLine("  };");
        sb.AppendLine("}");
        sb.AppendLine("}");
        return SourceText.From(sb.ToString(), Encoding.UTF8);
    }

    static SourceText ExpandInLibrary(ImmutableArray<SourceFileInfo> sources)
    {
        StringBuilder sb = new();
        StringBuilder inner = new();
        var usings = new HashSet<string>();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("namespace SourceExpander.Embedded.Expand{");
        foreach (var s in sources)
        {
            usings.UnionWith(s.Usings);
            inner.AppendLine(s.CodeBody);
        }
        foreach (var s in usings)
            sb.AppendLine(s);
        sb.AppendLine(inner.ToString());
        sb.AppendLine("}");

        return SourceText.From(sb.ToString(), Encoding.UTF8);
    }

    internal static EmbedderConfig
        ParseConfigWithDiagnostic(IContextWrappter ctx, EmbedderConfig.Builder builder, AnalyzerConfigOptions analyzerConfigOptions)
    {
        ctx.CancellationToken.ThrowIfCancellationRequested();
        var isDesignTimeBuild = StringComparer.OrdinalIgnoreCase.Equals(
            analyzerConfigOptions.GetOrNull("build_property.DesignTimeBuild"),
            "true");
        if (isDesignTimeBuild)
            return new EmbedderConfig(false);

        ctx.CancellationToken.ThrowIfCancellationRequested();
        try
        {
            var config = builder.Build(ctx.CancellationToken);

            if (config.ObsoleteConfigProperties.Any())
            {
                foreach (var p in config.ObsoleteConfigProperties)
                {
                    ctx.ReportDiagnostic(
                        DiagnosticDescriptors.EMBED0011_ObsoleteConfigProperty(builder.SourceText?.Path, p.Name, p.Instead));
                }
            }
            return config;
        }
        catch (ParseJsonException e)
        {
            ctx.ReportDiagnostic(DiagnosticDescriptors.EMBED0003_ParseConfigError(builder.SourceText?.Path, e.Message));
            return new EmbedderConfig();
        }
    }
}
